### ISSUE TITLE
repeat time function

### ISSUE THREAD

**Issue by vb2cans** [fernadosilva/orvfms#3] opened 2015-11-03 05:39 UTC
When you add a repeat time function and set the Action to ON
Click on the Done button it reads that it will turn OFF not ON

**Comment by fernadosilva** [comment] 2015-11-03 18:43
Thank you. Yes, I noticed that yesterday I  committed a buggy version with that problem (a change of variable name with undesired side effects). I only noticed it a few hours later. Can you please try to download the current version and check if the problem is solved? I believe it is OK now.

**Comment by vb2cans** [comment] 2015-11-03 21:43
Hi All fixed now.

Is there a way to be able to show all Days the timer is set for on the main page. Instead of just one day.

Kind Regards

Steve Davis

**Comment by fernadosilva** [comment] 2015-11-04 11:55
Great, thanks!

Not sure if I am able to put everything on the main page given that my main goal is to keep a responsive web interface in order to control the devices from my smartphone.  Unhappily, I am not a web design expert and I already went well beyond my original target (my first purpose was only to have the switch on and switch off functional). I am afraid that if I put too much information in the main page it will become unusable in a small screen (and I have 5 S20s at home...). But I am considering to put a hook/button in the main page to go directly to the timers page. 

I can also add the current status and may be a on/off switch to the page where the timers of given device are displayed. This would make possible to have a GET URL to redirect the user directly to a given device page. On other words, one could redefine one subsidiary "main page" for each device with all the information and operation of a given device. This would be easier than have all information from all devices in the main page. What do you think?

**Comment by vb2cans** [comment] 2015-11-04 21:03
Hi,

Firstly I would like to thank you for all your hard work and time you have but into this project.

Having all the information in one page would be good.

Kind Regards

**Closed as completed** 2015-11-04 21:30 UTC

**Comment by fernadosilva** [comment] 2015-11-05 11:56
Check the current version. Not exactly what you requested, but now I show the next 3 scheduled events in the main page. I expect this will cover at least most of daily events. You may increase the number of displayed events changing the value of the last constant in globals.php, but I will not do it by default because the display in small screen becomes too dense.

Reds,
